---
- hosts: all
  tasks:
      - name: test lest
        debug:
                msg: "current is: {{ 'development' if dev_env else 'not development' }}"

        # this is the task to run netplan on all the hosts
#      - name: netplan apply to get the default gateway reset
#        shell: netplan apply
#        become: true
#        become_user: root
