- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: save join command
      local_action: copy content={{ join_command_raw.stdout_lines[0] }} dest=./join-command
#    - name: set join command
#      set_fact:
#        join_command: "{{ join_command_raw.stdout_lines[0] }}"

#    - name: save join command
#      shell: "echo \"{{ hostvars['node0'].join_command }}\" >> join_cmd.txt"
#      args:
#        chdir: $HOME
#        creates: join_cmd.txt


- hosts: workers
  become: yes
  tasks:
    - name: get join commmand from rooster
      copy: src=./join-command dest=/tmp/join-command.sh mode=0777

    - name: join the node to cluster
      command: sh /tmp/join-command.sh

  handlers:
    - name: start Docker
      service: name=docker state=started

