- hosts: all
  become: yes
  tasks:
    - name: allow 'spicy' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'spicy ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: create ~/.ssh/ directory
      become: yes
      become_user: spicy
      file:
        path: $HOME/.ssh
        state: directory
        mode: 0755

    - name: set up authorized keys for the ubuntu user
      authorized_key: user=spicy key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: disable swap for kubelet to work
      shell: swapoff -a
